# No Thunderbolt hardware
blacklist thunderbolt

# No FireWire hardware
blacklist firewire_core
blacklist firewire_ohci
blacklist firewire_sbp2

# No floppy controller
blacklist floppy

# No internal PC speaker
blacklist pcspkr

# No parallel port
blacklist parport
blacklist parport_pc
blacklist ppdev

# No legacy serial ports
blacklist serial8250
blacklist 8250_pnp

# No PS/2 mouse
blacklist psmouse          # note: can block touchpad on laptops / mouse input in VMs

# No CD/DVD/BluRay drive
blacklist sr_mod           # note: required for ISO mounting in virt-manager (VM virtual CD-ROM)
blacklist cdrom            # note: required for ISO mounting in virt-manager (VM virtual CD-ROM)

# No ATA optical support
blacklist pata_acpi
blacklist pata_atiixp
blacklist pata_jmicron

# No legacy SCSI controllers
blacklist megaraid
blacklist mptbase
blacklist mptscsih
blacklist aic7xxx
blacklist aic79xx

# No game controllers
blacklist joydev           # note: remove if using a gamepad