
#!/usr/bin/env bash

# ==============================================================================
# ArchGuard - Configuration Backup Paths
# ==============================================================================
# /configs/backup-file-paths.conf

declare -gA BACKUP_PATHS=(

    # Neovim
    ["nvim"]="/home/willem/.config/nvim"

    # SDDM
    ["sddm"]="/etc/sddm.conf"

    # KDE Plasma
    ["kde-global"]="/home/willem/.config/kdeglobals"
    ["kde-shortcuts"]="/home/willem/.config/kglobalshortcutsrc"
    ["kde-window-manager"]="/home/willem/.config/kwinrc"

    # Back Grounds
    ["Background"]="/home/willem/Pictures/BackGround"
    # ["Background"]="/home/willem/Pictures/BackGround/Login.png"

    # Add more configuration paths below
    # ["example"]="/other/config/files"
)
