#!/usr/bin/env bash
# ==============================================================================
#  Arch Secure Installer V2.6 — Secure Boot Certificate Information
# ==============================================================================
#  lib/prepare/system/cert_info.sh
#
#  Displays information about the available Secure Boot certificate modes.
#
#  Does not modify configuration.
# ==============================================================================

cert_info()
{
    clear

    printf '%s\n' "================================================================================"
    printf '%s\n' " Secure Boot Certificate Options"
    printf '%s\n\n' "================================================================================"

    printf '%s\n' " [1] Custom"
    printf '%s\n' "     Uses certificates generated by this installer."
    printf '\n'

    printf '%s\n' "     Before enrollment:"
    printf '%s\n' "       UEFI Secure Boot must be in Setup Mode."
    printf '%s\n' "       This normally means the Platform Key (PK) is removed."
    printf '\n'

    printf '%s\n' "     Advantages:"
    printf '%s\n' "       + Maximum control over what can boot."
    printf '%s\n' "       + Only software signed with your keys is trusted."
    printf '%s\n' "       + No dependency on Microsoft's certificates."
    printf '\n'

    printf '%s\n' "     Disadvantages:"
    printf '%s\n' "       - Other unsigned or differently-signed boot media will not boot."
    printf '%s\n' "       - You are responsible for signing your own boot files."
    printf '%s\n' "       - Some hardware may require Microsoft's certificates."
    printf '\n'

    printf '%s\n' " [2] Microsoft"
    printf '%s\n' "     Uses the Microsoft Secure Boot trust chain."
    printf '\n'

    printf '%s\n' "     Advantages:"
    printf '%s\n' "       + Easiest option."
    printf '%s\n' "       + No custom certificates need to be created."
    printf '%s\n' "       + Broad compatibility with Microsoft-signed software."
    printf '\n'

    printf '%s\n' "     Disadvantages:"
    printf '%s\n' "       - Less restrictive than Custom-only."
    printf '%s\n' "       - You trust Microsoft's Secure Boot infrastructure."
    printf '%s\n' "       - Less control over third-party EFI software."
    printf '\n'

    printf '%s\n' " [3] Custom with Microsoft available"
    printf '%s\n' "     Uses your certificates while retaining Microsoft's certificates."
    printf '\n'

    printf '%s\n' "     Before enrollment:"
    printf '%s\n' "       UEFI Secure Boot must be in Setup Mode."
    printf '%s\n' "       This normally means the Platform Key (PK) is removed."
    printf '\n'

    printf '%s\n' "     Advantages:"
    printf '%s\n' "       + Your keys control your Arch installation."
    printf '%s\n' "       + Microsoft-signed EFI software remains trusted."
    printf '%s\n' "       + Better compatibility with other boot media."
    printf '%s\n' "       + Good balance between security and compatibility."
    printf '\n'

    printf '%s\n' "     Disadvantages:"
    printf '%s\n' "       - More setup than Microsoft-only."
    printf '%s\n' "       - You still trust Microsoft's certificates."
    printf '%s\n' "       - Less restrictive than Custom-only."
    printf '\n'

    printf '%s\n' "--------------------------------------------------------------------------------"
    printf '%s\n' " Press Enter to return"
    printf '%s\n' "--------------------------------------------------------------------------------"

    read -r
}