#!/usr/bin/env bash
# ==============================================================================
#  Arch Secure Installer V2.6 — Secure Boot Certificate Information
# ==============================================================================
#  lib/prepare/system/cert_info.sh
#
#  Displays information about the available Secure Boot certificate modes.
#
#  Does not modify configuration.
# ==============================================================================

cert_info()
{
    clear

    printf "================================================================================\n"
    printf " Secure Boot Certificate Options\n"
    printf "================================================================================\n\n"

    printf " [1] Custom\n"
    printf "     Your system uses certificates generated by this installer.\n"
    printf "\n"
    printf "     Before the certificates can be enrolled, the UEFI must be placed\n"
    printf "     into Setup Mode. Setup Mode means the Platform Key (PK) has been\n"
    printf "     removed, allowing new Secure Boot keys to be enrolled.\n"
    printf "\n"
    printf "     Advantages:\n"
    printf "       + Maximum control over what is allowed to boot.\n"
    printf "       + Only software signed with your trusted keys can boot.\n"
    printf "       + No dependency on Microsoft's Secure Boot certificates.\n"
    printf "\n"
    printf "     Disadvantages:\n"
    printf "       - Other unsigned or differently-signed boot media will not boot\n"
    printf "         while Secure Boot is enabled.\n"
    printf "       - You are responsible for signing your own boot files.\n"
    printf "       - Some hardware firmware or option ROMs may require Microsoft's\n"
    printf "         certificates to function during the pre-boot stage.\n"
    printf "\n"

    printf " [2] Microsoft\n"
    printf "     Uses the Microsoft Secure Boot trust chain already provided by\n"
    printf "     the system firmware.\n"
    printf "\n"
    printf "     Advantages:\n"
    printf "       + Easiest option.\n"
    printf "       + No custom certificates need to be created or enrolled.\n"
    printf "       + Broad compatibility with Microsoft-signed boot software.\n"
    printf "\n"
    printf "     Disadvantages:\n"
    printf "       - Less restrictive than using only your own certificates.\n"
    printf "       - You are trusting Microsoft's Secure Boot signing infrastructure.\n"
    printf "       - You do not get the same level of control over what third-party\n"
    printf "         EFI software is trusted to boot.\n"
    printf "\n"

    printf " [3] Custom with Microsoft available\n"
    printf "     Uses your own certificates while also retaining Microsoft's\n"
    printf "     certificates in the UEFI trust database.\n"
    printf "\n"
    printf "     Before the certificates can be enrolled, the UEFI must be placed\n"
    printf "     into Setup Mode.\n"
    printf "\n"
    printf "     Advantages:\n"
    printf "       + Your own keys control your Arch installation and its boot files.\n"
    printf "       + Microsoft-signed EFI software remains trusted.\n"
    printf "       + Better compatibility with other bootable media and hardware\n"
    printf "         whose pre-boot firmware is signed by Microsoft.\n"
    printf "       + Good balance between security, control, and compatibility.\n"
    printf "\n"
    printf "     Disadvantages:\n"
    printf "       - More setup is required than Microsoft-only.\n"
    printf "       - You still trust Microsoft's Secure Boot certificates.\n"
    printf "       - It does not provide the same restrictive trust boundary as\n"
    printf "         Custom-only.\n"
    printf "\n"

    printf "--------------------------------------------------------------------------------\n"
    printf " Setup Mode\n"
    printf "--------------------------------------------------------------------------------\n"
    printf "\n"
    printf " Custom and Custom with Microsoft available require the UEFI to be in\n"
    printf " Setup Mode before the custom keys can be enrolled.\n"
    printf "\n"
    printf " Setup Mode normally means that the Platform Key (PK) has been removed.\n"
    printf " The exact procedure for entering Setup Mode depends on the motherboard\n"
    printf " or system manufacturer.\n"
    printf "\n"
    printf " Microsoft-only does not require custom key enrollment.\n"
    printf "\n"

    printf "================================================================================\n"
    printf " Press Enter to return\n"
    printf "================================================================================\n"

    read -r
}