#!/usr/bin/env bash
# ==============================================================================
#  Arch Secure Installer V2.6 — Secure Boot Certificate Information
# ==============================================================================
#  lib/prepare/system/cert_info.sh
#
#  Displays information about the available Secure Boot certificate modes.
#
#  Does not modify configuration.
# ==============================================================================

cert_info()
{
    clear

    printf '%s\n' "================================================================================"
    printf '%s\n' " Secure Boot Certificate Options"
    printf '%s\n\n' "================================================================================"

    printf '%s\n' " [1] Custom"
    printf '%s\n' "     Uses certificates generated by this installer."
    printf '%s\n' "     Only your custom Secure Boot certificates are enrolled."
    printf '\n'

    printf '%s\n' "     Before enrollment:"
    printf '%s\n' "       UEFI Secure Boot must be in Setup Mode."
    printf '%s\n' "       This normally means the Platform Key (PK) is removed."
    printf '\n'

    printf '%s\n' "     Advantages:"
    printf '%s\n' "       + Maximum control over what can boot."
    printf '%s\n' "       + Your UKI is signed with your own Secure Boot key."
    printf '%s\n' "       + Only software trusted by your enrolled keys is accepted."
    printf '%s\n' "       + No Microsoft certificates are enrolled."
    printf '\n'

    printf '%s\n' "     Disadvantages:"
    printf '%s\n' "       - Other Microsoft-signed EFI software will not be trusted."
    printf '%s\n' "       - You are responsible for signing your own boot files."
    printf '%s\n' "       - Some recovery or third-party boot media may not work."
    printf '\n'

    printf '%s\n' " [2] Microsoft"
    printf '%s\n' "     Uses your custom signing keys while also retaining"
    printf '%s\n' "     Microsoft's Secure Boot certificates."
    printf '\n'

    printf '%s\n' "     Before enrollment:"
    printf '%s\n' "       UEFI Secure Boot must be in Setup Mode."
    printf '%s\n' "       This normally means the Platform Key (PK) is removed."
    printf '\n'

    printf '%s\n' "     Signing:"
    printf '%s\n' "       Your UKI is still signed with your own Secure Boot key."
    printf '%s\n' "       Microsoft's private signing keys are never used."
    printf '%s\n' "       Microsoft's certificates are additionally trusted by UEFI."
    printf '\n'

    printf '%s\n' "     Advantages:"
    printf '%s\n' "       + Your Arch installation is signed with your own keys."
    printf '%s\n' "       + Microsoft-signed EFI software remains trusted."
    printf '%s\n' "       + Better compatibility with other boot and recovery media."
    printf '%s\n' "       + Uses your keys without giving up Microsoft's trust chain."
    printf '\n'

    printf '%s\n' "     Disadvantages:"
    printf '%s\n' "       - You also trust Microsoft's Secure Boot certificates."
    printf '%s\n' "       - Less restrictive than Custom-only."
    printf '%s\n' "       - Microsoft-signed EFI software can be trusted by the firmware."
    printf '\n'

    printf '%s\n' "--------------------------------------------------------------------------------"
    printf '%s\n' " Press Enter to return"
    printf '%s\n' "--------------------------------------------------------------------------------"

    read -r
}